import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as Material from '@mui/material';
import * as transactionApi from '../data/transactionApi';

export default function Home() {

  // const [transId, setTransId] = React.useState('');
  // const [transId, setTransId] = React.useState('');
  // const [transId, setTransId] = React.useState('');
  // const [transId, setTransId] = React.useState('');

  async function getAllData () {
    const result = await transactionApi.getAllTransaction();
    console.log(result);
  }

  async function saveData() {
    const result = await transactionApi.saveTransaction({
      trans_id: 'TRX00003',
      vendor_name: 'Abadi Jaya Barokah',
      vendor_address: 'Jalan Kesana Kemari',
      pic: 'Wagimin',
      purchase_dt: '{format : yyyymmdd}',
      received_dt: '{format : yyyymmdd}',
      create_by:	'{yourName}',
      create_dt: '{format : yyyymmddhhii}',
    });
  }

  React.useEffect(() => {
    getAllData();
  } ,[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Material.Paper>
          
        </Material.Paper>
      </main>
    </div>
  )
}
